googleAnalytics = 'UA-36085609-4'
baseURL = 'http://ee.web3box.dev/'
languageCode = 'zh-cn'
title = 'Web3ä¼ä¸šçº§å·¥ç¨‹'
theme = "hugo-book"
[params]
    # (Optional) If you have enabled BookComments for the site, you can disable it for specific pages.
    BookServiceWorker = true
    BookTheme = 'dark'
    BookSection = '*'
    description = 'Web3ä¼ä¸šçº§å·¥ç¨‹å¼€å‘æŒ‡å—ï¼Œè¯¥ç³»åˆ—å†…å®¹ä¸ºWeb3å¼€å‘ä¸­å·¥ç¨‹åŒ–æ‰€é‡åˆ°çš„å„ç§é—®é¢˜æŒ‡å—ï¼ŒåŒ…å«å¼€å‘éƒ¨ç½²æµ‹è¯•ç­‰ä¸€äº›åˆ—é—®é¢˜çš„è§£å†³æ–¹æ¡ˆã€‚Made with â¤ï¸ by Web3Box'
    images = ['images/primary_banner.png']
    title = 'Web3ä¼ä¸šçº§å·¥ç¨‹'
[taxonomies]
    series = 'series'
[menu]
[[menu.before]]
  name = "ğŸ¦ @BoxMrChen çš„ æ¨ç‰¹"
  url = "https://twitter.com/BoxMrChen"
  weight = 10
[[menu.before]]
  name = "ğŸ«‚ å¾®ä¿¡ç¾¤ï¼ˆè¿˜æ²¡æœ‰ï¼‰"
  url = "#"
  weight = 20
[[menu.before]]
  name = "ğŸ“– Githubä»“åº“"
  url = "https://github.com/nishuzumi/Web3-Enterprise-level-engineering"
  weight = 30
[[menu.before]]
  name = "ğŸ¼ ETHåœ°å€ boxchen.eth"
  url = "https://etherscan.io/enslookup-search?search=boxchen.eth"
  weight = 40
[markup]
    [markup.highlight]
        style = 'paraiso-dark'
